### ISSUE TITLE
[Compat] Compatibility with Farmer's Delight Refabricated [Fabric 1.20.1]

### ISSUE THREAD

**Issue by mpustovoi** [mrsterner/BrewinAndChewin-Fabric#8]
Suggestion for compatibility with the new Farmer's Delight Fabric port:
https://modrinth.com/mod/farmers-delight-refabricated

> It offers more support for a better port which is more faithful to the original mod on Forge, and is cleaner internally and has less bugs.

Just saying here because maybe you don't know.

**Comment by mrsterner** [comment]
Already in working on that

**Comment by mrsterner** [comment]
done
