### ISSUE TITLE
[Bug] GUI of the keg is not displayed correctly in refabricated version

### ISSUE THREAD

**Issue by 7fish-can** [mrsterner/BrewinAndChewin-Fabric#9]
![keg-display](https://github.com/mrsterner/BrewinAndChewin-Fabric/assets/167167636/0e261e91-12d2-4afc-a5ce-7a74e511b2ea)

minecraft version: 1.20.1
fabric and api version: 0.15.10 + 0.92.1
Farmer's Delight Refabricated version: 2.0.16

The GUI is misaligned and missing temperature labels. I've tried running without any other mod, the problem with the display still persists.

**Comment by mrsterner** [comment]
Oh, fixed in the next update
